"""adds hilldb table

Revision ID: 1c4f67815aa0
Revises: 
Create Date: 2023-01-23 00:16:16.764838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c4f67815aa0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hilldb',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('analysis', sa.Integer(), nullable=True),
    sa.Column('signals', sa.Integer(), nullable=True),
    sa.Column('screenshot', sa.Integer(), nullable=True),
    sa.Column('help', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hilldb')
    # ### end Alembic commands ###
