"""adds hilldb table

Revision ID: 1dfa54578cbb
Revises: 3c97fb79c537
Create Date: 2023-01-25 12:41:29.000584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfa54578cbb'
down_revision = '3c97fb79c537'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hilldb',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('analysis', sa.Integer(), nullable=True),
    sa.Column('signals', sa.Integer(), nullable=True),
    sa.Column('screenshot', sa.Integer(), nullable=True),
    sa.Column('help', sa.Integer(), nullable=True),
    sa.Column('analysis_target', sa.Integer(), nullable=True),
    sa.Column('signals_target', sa.Integer(), nullable=True),
    sa.Column('screenshot_target', sa.Integer(), nullable=True),
    sa.Column('help_target', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hilldb')
    # ### end Alembic commands ###
