"""adds overall_statistic table

Revision ID: 1f77f2cf5f50
Revises: 4d85e7c86b22
Create Date: 2023-01-26 14:08:02.334002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f77f2cf5f50'
down_revision = '4d85e7c86b22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
