"""adds individual_statistic table

Revision ID: 4d85e7c86b22
Revises: 1dfa54578cbb
Create Date: 2023-01-25 21:37:13.236399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d85e7c86b22'
down_revision = '1dfa54578cbb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
