"""adds individual_statistic table

Revision ID: 91856fc4bbb9
Revises: 1f77f2cf5f50
Create Date: 2023-01-26 14:08:20.957452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91856fc4bbb9'
down_revision = '1f77f2cf5f50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
